export {
  ensureDataLayer,
  getCookie,
  generateEventId,
  newEventId,
  pushDataLayer,
  pushTrackingConfig,
  captureMarketingAttribution,
  getMarketingContext,
  trackPageView,
  trackViewContent,
  trackLead,
  trackContact,
  trackBeginCheckout,
  extractGtmId,
  buildDefaultHeadSnippet,
  buildDefaultHeadHtml,
  buildDefaultBodyHtml,
  normalizeGtmSettings,
  applyGtmHead,
  applyGtmBody,
  applyGtmSnippets,
  observeViewContent,
} from './dataLayer.js'
